### ISSUE TITLE
Is not setting right locale

### ISSUE THREAD

**Issue by IgorDePaula** [vyuldashev/nova-money-field#20] opened 2018-12-31 10:03 UTC
![captura de tela de 2018-12-31 07-58-45](https://user-images.githubusercontent.com/2833993/50558086-2ed6b800-0cd2-11e9-8dab-928b42026835.png)
![captura de tela de 2018-12-31 07-58-52](https://user-images.githubusercontent.com/2833993/50558087-2ed6b800-0cd2-11e9-8a8e-5b57a9b1c572.png)
In price, in pt-BR, should like "0,04" , and only have "BRL" because I put it. This component not respect the locale on method locale or locale on config/app.php

**Comment by vyuldashev** [comment] 2019-01-04 17:52
Duplicate of #5 

Please, make an implementation suggestion or create a PR for this feature.

**Closed by vyuldashev** 2019-01-04 17:52 UTC
